import AppShell from "@/components/app-shell";
import { Card, Gauge, Heatmap } from "@/components/ui";

export default function GrowthInsightsPage() {
  return (
    <AppShell title="Growth Insights" subtitle="AI-powered recommendations for audience growth">
      <div className="mb-6"><div className="kicker">Recommendation engine</div><h1 className="mt-2 text-3xl font-semibold tracking-[-.045em] text-white">Growth Insights</h1><p className="muted mt-2 text-sm">Turn historical engagement into simple, explainable next actions.</p></div>
      <div className="grid gap-4 xl:grid-cols-[340px_1fr]"><Card className="neon-border p-6"><h2 className="font-semibold text-white">Overall health</h2><div className="mt-3"><Gauge score={85}/></div><p className="muted text-center text-sm leading-6">Your account is performing in the top range of your recent baseline.</p></Card><Card className="p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold text-white">Optimal posting schedule</h2><p className="muted mt-1 text-xs">Based on your highest engagement windows</p></div><div className="pill">High confidence</div></div><div className="mt-6"><Heatmap/></div><div className="mt-5 rounded-xl border border-emerald-300/10 bg-emerald-300/[.035] p-3 text-xs text-[#9bcdb9]">Best window: Tuesday and Friday, 7 PM to 9 PM.</div></Card></div>
      <Card className="mt-4 p-6"><div className="flex items-center gap-2"><span className="text-violet-300">✦</span><h2 className="font-semibold text-white">AI recommended actions</h2></div><div className="mt-5 grid gap-4 md:grid-cols-3">{[["Prioritize educational saves","Carousel and checklist posts are producing 31% more saves than lifestyle content. Increase this mix next week.","Review content mix"],["Protect your peak window","Schedule your strongest posts between 7 PM and 9 PM instead of midday for better initial velocity.","Open calendar"],["Strengthen CTA clarity","Recent captions have strong hooks but weaker next-step prompts. Make the final CTA outcome-specific.","Analyze captions"]].map(([t,d,a],i)=><div key={t} className="relative overflow-hidden rounded-2xl border border-white/[.055] bg-white/[.018] p-5"><div className="absolute inset-x-0 top-0 h-[3px] bg-gradient-to-r from-violet-400 to-emerald-300" style={{opacity:.3+i*.13}}/><div className="grid h-10 w-10 place-items-center rounded-xl bg-violet-500/10 text-violet-200">{i===0?"◇":i===1?"◷":"✦"}</div><h3 className="mt-4 font-semibold text-white">{t}</h3><p className="muted mt-2 text-sm leading-6">{d}</p><button className="mt-5 text-xs font-semibold text-violet-300">{a} ↗</button></div>)}</div></Card>
    </AppShell>
  );
}
