"use client";

import { FormEvent, useState } from "react";
import AppShell from "@/components/app-shell";
import { Card } from "@/components/ui";
import { apiFetch } from "@/lib/api";

export default function SettingsPage() {
  const [saved,setSaved] = useState(false);
  const [error,setError] = useState("");
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaved(false);setError("");const form=new FormData(e.currentTarget);try{await apiFetch("/api/v1/users/me",{method:"PUT",body:JSON.stringify({name:form.get("name"),bio:form.get("bio")})});setSaved(true);}catch(err){setError(err instanceof Error?err.message:"Could not save profile");}}
  return (
    <AppShell title="Settings" subtitle="Profile, security and workspace preferences">
      <div className="mb-6 flex gap-2 overflow-x-auto hide-scrollbar">{["Profile","Account","Notifications","Billing","API","Integrations"].map((t,i)=><button key={t} className={`pill shrink-0 ${i===0?"border-violet-300/30 bg-violet-500/10 text-violet-100":""}`}>{t}</button>)}</div>
      <Card className="p-6 sm:p-8"><div className="border-b border-white/[.055] pb-6"><h1 className="text-xl font-semibold text-white">Profile information</h1><p className="muted mt-2 text-sm">Manage your public profile and account details.</p></div><form onSubmit={submit} className="mt-7"><div className="grid gap-8 lg:grid-cols-[1fr_220px]"><div className="space-y-5"><label className="block"><span className="label mb-2 block">Full name</span><input name="name" className="field" defaultValue="Creator User"/></label><label className="block"><span className="label mb-2 block">Email</span><input name="email" type="email" className="field opacity-70" defaultValue="creator@example.com" disabled/><span className="mt-2 block text-[10px] text-[#657189]">Email changes are intentionally disabled in the current MVP.</span></label><label className="block"><span className="label mb-2 block">Bio</span><textarea name="bio" className="field min-h-32 resize-none" defaultValue="Building with CreatorOS AI to create smarter content and grow with data."/><span className="mt-2 block text-[10px] text-[#657189]">Brief description for your profile.</span></label></div><div className="border-l border-white/[.055] pl-0 lg:pl-8"><div className="label mb-3 text-center">Profile image</div><div className="mx-auto grid h-32 w-32 place-items-center rounded-full border border-violet-300/15 bg-gradient-to-br from-violet-500/18 via-[#0d1529] to-emerald-300/[.06] text-3xl font-semibold text-violet-100 shadow-[0_0_35px_rgba(124,58,237,.12)]">CR</div><button type="button" className="secondary-btn mx-auto mt-4 flex">Change photo</button></div></div>{error&&<div className="mt-5 rounded-xl border border-rose-300/10 bg-rose-400/[.06] p-3 text-xs text-rose-200">{error}</div>}<div className="mt-8 flex flex-wrap items-center justify-end gap-3 border-t border-white/[.055] pt-6">{saved&&<span className="mr-auto text-xs font-semibold text-[#4edea3]">✓ Changes saved</span>}<button type="button" className="secondary-btn">Cancel</button><button className="primary-btn">Save changes</button></div></form></Card>
      <div className="mt-4 grid gap-4 md:grid-cols-2"><Card className="p-6"><div className="kicker">Security</div><h2 className="mt-2 font-semibold text-white">Password & sessions</h2><p className="muted mt-2 text-sm leading-6">Update your password and review active CreatorOS sessions.</p><button className="secondary-btn mt-5">Change password</button></Card><Card className="p-6"><div className="kicker">Data controls</div><h2 className="mt-2 font-semibold text-white">Privacy & exports</h2><p className="muted mt-2 text-sm leading-6">Export account data or review how connected platform information is handled.</p><button className="secondary-btn mt-5">Manage data</button></Card></div>
    </AppShell>
  );
}
